use crate::config::AppConfig;
use std::path::Path;

pub const AGENT_TEMPLATE: &str = include_str!("../../config/agent/AGENTS.md");
const BASE_INSTRUCTIONS: &str = include_str!("../../config/agent/BASE_INSTRUCTIONS.md");

pub async fn ensure_agent_file(home: &Path) -> Result<(), String> {
    use tokio::io::AsyncWriteExt;
    tokio::fs::create_dir_all(home)
        .await
        .map_err(|e| e.to_string())?;
    match tokio::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(home.join("AGENTS.md"))
        .await
    {
        Ok(mut file) => file
            .write_all(AGENT_TEMPLATE.as_bytes())
            .await
            .map_err(|e| e.to_string()),
        Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => Ok(()),
        Err(e) => Err(format!("无法创建默认 AGENTS.md：{e}")),
    }
}

pub fn environment(config: &AppConfig, cwd: &str) -> String {
    let shell = if cfg!(windows) {
        &config.terminal.windows_shell
    } else {
        &config.terminal.unix_shell
    };
    let network = if config.network.proxy_url.trim().is_empty() {
        "Use host network settings; no FluxCode proxy is configured.".to_owned()
    } else {
        format!(
            "FluxCode proxy for outbound traffic: {}",
            config.network.proxy_url
        )
    };
    format!(
        "You are working inside FluxCode desktop.\nEnvironment facts:\n- OS: {}\n- Architecture: {}\n- Project root: {}\n- Interactive command-panel shell: {}\n- Agent shell tools: use the engine-provided schema and reported environment.\n- Bundled Codex engine: {}\n- Model transport: Responses API\n- Sandbox: danger-full-access\n- Approval policy: never\n- Network: {}\n- Text encoding: UTF-8, explicit on read/write\n- Runtime: local desktop; inspect installed build tools before use.\nAsk for missing user information in normal messages. Do not invoke interactive question tools unsupported by this client.\n",
        std::env::consts::OS,
        std::env::consts::ARCH,
        cwd,
        shell,
        env!("FLUXCODE_ENGINE_VERSION"),
        network
    )
}

pub fn instructions(config: &AppConfig, cwd: &str) -> String {
    format!("{BASE_INSTRUCTIONS}\n\n{}", environment(config, cwd))
}

pub async fn write_environment(home: &Path, config: &AppConfig) -> Result<(), String> {
    let text = format!(
        "# FluxCode environment\n\nGenerated by FluxCode. User instructions belong in AGENTS.md, which is never overwritten.\n\n{}",
        environment(
            config,
            "Selected per task; supplied in each task's environment context"
        )
    );
    tokio::fs::write(home.join("ENVIRONMENT.md"), text)
        .await
        .map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[tokio::test]
    async fn preserves_custom_agent_instructions() {
        let dir = tempfile::tempdir().unwrap();
        ensure_agent_file(dir.path()).await.unwrap();
        tokio::fs::write(dir.path().join("AGENTS.md"), "Custom instructions")
            .await
            .unwrap();
        ensure_agent_file(dir.path()).await.unwrap();
        assert_eq!(
            tokio::fs::read_to_string(dir.path().join("AGENTS.md"))
                .await
                .unwrap(),
            "Custom instructions"
        );
    }
}
